### ISSUE TITLE
Bump to 0.6.0

### ISSUE THREAD

**Issue by jordantshaw** [conda-forge/pandas_flavor-feedstock#10]
### Comment:

The latest version available in conda-forge is 0.2.0 https://anaconda.org/conda-forge/pandas-flavor

Can we get this bumped up to the latest version of 0.6.0?

@ocefpaf @Zsailer

**Comment by ocefpaf** [comment]
I believe that version with the - instead of the _ was deprecated. See https://anaconda.org/conda-forge/pandas_flavor/files

We could create an alias to help folks with that.

**Comment by jordantshaw** [comment]
Thanks for the reply.  That should solve my issue.  And agreed, an alias may help, thanks!
